---
- name: Install required packages
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Docker apt key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
